function create_table(objects,table_name,scenario_name)

% initialized table for the corresponding scenario
%
% Agostini - 14.12.2018



for i=1:length(objects)
    object = objects(i);
    % time = 0;
    variables = object.variables;
    for j=1:length(variables)
        variable = variables(j);
        time = variables(j).time;
        id = variable.id;        
        request = ['insert into ' scenario_name '_' table_name...
                   ' (id,' ...
                   'time,'...
                   'obj,'...
                   'var,'...
                   'val,'...
                   'flag) '...
                   'values ('...
                   num2str(id) ','...
                   '''' num2str(time) ''','...
                   '''' num2str(object.name) ''','...
                   '''' num2str(variable.name) ''','...
                   '''' num2str(variable.value) ''','...
                   num2str(0) ...
                   ')'];
        mexSqlRequestRWScalar_uniphyed(request);  
        % disp(request)
    end
end